name: muhammad_ali_portfolio
description: A Flutter portfolio website for Muhammad Ali
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.11
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  animated_text_kit: ^4.2.2
  provider: ^6.0.5
  http: ^1.1.0
  flutter_svg: ^2.0.7
  scrollable_positioned_list: ^0.3.8
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
 